- repo: https://github.com/OCA/pylint-odoo
        rev: v9.1.2 # may be a tag or commit hash
        hooks:
        # Add to your .pylintrc file:
        # [MASTER]
        # load-plugins=pylint_odoo
        - id: pylint_odoo
