name: Deploy to Test Server

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Test Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_SERVER_HOST }}
        username: ${{ secrets.TEST_SERVER_USERNAME }}
        key: ${{ secrets.TEST_SERVER_SSH_KEY }}
        script: |
          cd /home/fresh_express/odoo-16-docker-compose/addons/test-precommit
          git pull 
          docker compose down
          docker compose up -d
          sleep 10 && python /home/fresh_express/odoo-16-docker-compose/addons/update.py clinique
          
          
