from . import patient
from . import rendezvous
from . import fichier
from . import diagnostic
from . import medecin
from . import maladie
from . import medicament
from . import symptome
from . import ordonnance
from . import operation
from . import horaire
from . import controllers
from . import paiment
